// Generates public/dc/gen/*.js from the Claude Design source files in design/.
//
// Each module exports the file's template and props metadata verbatim, and its
// `class Component extends DCLogic {…}` source verbatim as the default export. Nothing is
// evaluated at build time; the output is plain static code that runs under a strict CSP.
//
//   node scripts/build-design.js
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const srcDir = path.join(root, 'design');
const outDir = path.join(root, 'public', 'dc', 'gen');

const decode = s => s.replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&amp;/g, '&');
export const slug = name => name.replace(/\.dc\.html$/, '').replace(/[^A-Za-z0-9]+/g, '-').replace(/^-|-$/g, '').toLowerCase();

fs.rmSync(outDir, { recursive: true, force: true });
fs.mkdirSync(outDir, { recursive: true });

const entries = [];
for (const file of fs.readdirSync(srcDir).filter(f => f.endsWith('.dc.html')).sort()) {
  const src = fs.readFileSync(path.join(srcDir, file), 'utf8');
  const open = src.match(/<x-dc(?:\s[^>]*)?>/);
  const close = src.lastIndexOf('</x-dc>');
  if (!open || close < 0) throw new Error(`${file}: no <x-dc> block`);
  const template = src.slice(open.index + open[0].length, close);

  const scriptOpen = src.match(/<script type="text\/x-dc" data-dc-script([^>]*)>/);
  let propsMeta = {};
  let logic = 'class Component extends DCLogic {\n  renderVals() { return {}; }\n}';
  if (scriptOpen) {
    const propsAttr = scriptOpen[1].match(/data-props="([^"]*)"/);
    if (propsAttr) propsMeta = JSON.parse(decode(propsAttr[1]));
    const start = scriptOpen.index + scriptOpen[0].length;
    logic = src.slice(start, src.indexOf('</script>', start)).trim();
  }
  if (!/^class Component extends DCLogic\b/.test(logic)) throw new Error(`${file}: unexpected logic shape`);

  const name = file.replace(/\.dc\.html$/, '');
  const mod = slug(file);
  fs.writeFileSync(path.join(outDir, `${mod}.js`), [
    `// GENERATED by scripts/build-design.js from design/${file}. Do not edit.`,
    `import { DCLogic } from '../runtime.js';`,
    `export const name = ${JSON.stringify(name)};`,
    `export const template = ${JSON.stringify(template)};`,
    `export const propsMeta = ${JSON.stringify(propsMeta)};`,
    `export default ${logic}`,
    '',
  ].join('\n'));
  entries.push({ name, mod, kind: name.startsWith('UI ') ? 'component' : 'screen' });
}

fs.writeFileSync(path.join(outDir, 'index.js'), [
  '// GENERATED by scripts/build-design.js. Do not edit.',
  `import { register } from '../runtime.js';`,
  ...entries.map((e, i) => `import * as m${i} from './${e.mod}.js';`),
  `export const modules = [${entries.map((_, i) => `m${i}`).join(', ')}];`,
  `export const screens = ${JSON.stringify(entries.filter(e => e.kind === 'screen').map(e => ({ name: e.name, slug: e.mod })))};`,
  'for (const m of modules) register({ name: m.name, template: m.template, propsMeta: m.propsMeta, Component: m.default });',
  '',
].join('\n'));

// Components only (what the app loads; screens are for the dev gallery).
const comps = entries.filter(e => e.kind === 'component');
fs.writeFileSync(path.join(outDir, 'components.js'), [
  '// GENERATED by scripts/build-design.js. Do not edit.',
  `import { register } from '../runtime.js';`,
  ...comps.map((e, i) => `import * as c${i} from './${e.mod}.js';`),
  `for (const m of [${comps.map((_, i) => `c${i}`).join(', ')}]) register({ name: m.name, template: m.template, propsMeta: m.propsMeta, Component: m.default });`,
  '',
].join('\n'));

console.log(`Generated ${entries.length} modules into public/dc/gen/`);
